"""Textos del embudo inmobiliario en 7 idiomas.

Cubre cinco situaciones: comprar, vender, buscar alquiler,
poner un inmueble en alquiler y colaboración entre agentes.
"""

TEXTOS_INMO = {
    # ------------------------------------------------ CASTELLANO
    "es": {
        "modo_ahorro": "💡 Ahorrar en mis servicios",
        "modo_inmo": "🏡 Vivienda: comprar, vender o alquilar",
        "modo_pregunta": "¿Qué te interesa?",
        "inmo_titulo": "🏡 ¿Compras, vendes o alquilas?",
        "inmo_intro": "Cuéntanos qué necesitas y te acompañamos en todo el proceso, "
                      "**sin compromiso**: valoración, búsqueda, papeleo y firma.",
        "inmo_paso1": "1️⃣ Tu operación",
        "inmo_paso2": "2️⃣ Tus datos de contacto",
        "inmo_sello": "🔑 Acompañamiento en todo el proceso",
        "inmo_sello_alq": "🤝 Colaboramos con otros agentes",
        "operacion": "¿Qué quieres hacer?",
        "operacion_opts": [
            "Comprar una vivienda",
            "Vender mi vivienda",
            "Busco piso de alquiler",
            "Quiero alquilar mi piso (soy propietario)",
            "Soy agente y quiero colaborar",
        ],
        "tipo": "Tipo de inmueble",
        "tipo_opts": ["Piso", "Casa o chalet", "Ático", "Local comercial",
                      "Terreno", "Otro"],
        "zona": "Ciudad y país del inmueble",
        "residencia": "¿Desde qué país nos escribes? (opcional)",
        "ambito": "🌍 Inmuebles en toda España · Atendemos a compradores y propietarios de otros países",
        "habitaciones": "Habitaciones",
        "importe_compra": "Presupuesto aproximado (€)",
        "importe_venta": "Precio que esperas (€)",
        "plazo": "¿Para cuándo?",
        "plazo_opts": ["Lo antes posible", "En unos 3 meses", "En unos 6 meses",
                       "Solo estoy mirando"],
        "financiacion": "¿Te interesa que revisemos la hipoteca?",
        "financiacion_opts": ["Sí, me interesa", "No, ya la tengo resuelta",
                              "Todavía no lo sé"],
        # --- busco alquiler
        "alq_presupuesto": "Presupuesto mensual (€/mes)",
        "alq_duracion": "¿Para cuánto tiempo?",
        "alq_duracion_opts": ["Menos de 1 año", "1 año", "2 años o más",
                              "Temporada o corta estancia"],
        "alq_entrada": "¿Desde cuándo lo necesitas?",
        "alq_personas": "¿Cuántas personas vivirán?",
        "alq_mascotas": "¿Tienes mascotas?",
        "alq_mascotas_opts": ["No", "Sí, pequeña", "Sí, grande"],
        "alq_situacion": "Situación laboral (opcional)",
        "alq_situacion_opts": ["Contrato indefinido", "Contrato temporal",
                               "Autónomo/a", "Estudiante", "Jubilado/a",
                               "Prefiero no decirlo"],
        "alq_acredita": "¿Puedes acreditar ingresos? (opcional)",
        "alq_acredita_opts": ["Sí", "Parcialmente", "Todavía no",
                              "Prefiero no decirlo"],
        # --- pongo en alquiler
        "prop_renta": "Renta mensual que esperas (€/mes)",
        "prop_amueblado": "¿Está amueblado?",
        "prop_amueblado_opts": ["Sí", "Parcialmente", "No"],
        "prop_disponible": "¿Desde cuándo está disponible?",
        "prop_mascotas": "¿Admites mascotas?",
        "prop_mascotas_opts": ["Sí", "No", "Según el caso"],
        "prop_gestion": "¿Qué necesitas?",
        "prop_gestion_opts": ["Solo encontrar inquilino",
                              "Gestión completa del alquiler",
                              "Todavía no lo sé"],
        # --- colaboración entre agentes
        "col_agencia": "Agencia o inmobiliaria",
        "col_zona": "Zona en la que trabajas",
        "col_tipo": "¿Qué tipo de colaboración buscas?",
        "col_tipo_opts": ["Compartir cartera de venta",
                          "Compartir cartera de alquiler",
                          "Busco comprador para un inmueble",
                          "Busco inquilino para un inmueble",
                          "Otra"],
        "col_cartera": "¿Cuántos inmuebles tienes en cartera?",
        "col_nota": "Cuéntanos brevemente qué buscas (opcional)",
        "inmo_boton": "🏡 Quiero que me asesoren",
        "col_boton": "🤝 Quiero colaborar",
        "inmo_gracias": "¡Gracias, {nombre}! 🏡 Te contactaremos muy pronto "
                        "para hablar de tu operación.",
        "col_gracias": "¡Gracias, {nombre}! 🤝 Te escribiremos para estudiar "
                       "la colaboración.",
        "privacidad_identificacion": "Puedes solicitar los datos identificativos "
                                     "completos del responsable escribiendo a {email}.",
    },
    # ------------------------------------------------ CATALÁN
    "ca": {
        "modo_ahorro": "💡 Estalviar en els meus serveis",
        "modo_inmo": "🏡 Habitatge: comprar, vendre o llogar",
        "modo_pregunta": "Què t'interessa?",
        "inmo_titulo": "🏡 Compres, vens o llogues?",
        "inmo_intro": "Explica'ns què necessites i t'acompanyem en tot el procés, "
                      "**sense compromís**: valoració, cerca, papers i signatura.",
        "inmo_paso1": "1️⃣ La teva operació",
        "inmo_paso2": "2️⃣ Les teves dades de contacte",
        "inmo_sello": "🔑 Acompanyament en tot el procés",
        "inmo_sello_alq": "🤝 Col·laborem amb altres agents",
        "operacion": "Què vols fer?",
        "operacion_opts": [
            "Comprar un habitatge",
            "Vendre el meu habitatge",
            "Busco pis de lloguer",
            "Vull llogar el meu pis (sóc propietari)",
            "Sóc agent i vull col·laborar",
        ],
        "tipo": "Tipus d'immoble",
        "tipo_opts": ["Pis", "Casa o xalet", "Àtic", "Local comercial",
                      "Terreny", "Altre"],
        "zona": "Ciutat i país de l'immoble",
        "residencia": "Des de quin país ens escrius? (opcional)",
        "ambito": "🌍 Immobles a tot Espanya · Atenem compradors i propietaris d'altres països",
        "habitaciones": "Habitacions",
        "importe_compra": "Pressupost aproximat (€)",
        "importe_venta": "Preu que esperes (€)",
        "plazo": "Per a quan?",
        "plazo_opts": ["Al més aviat possible", "En uns 3 mesos",
                       "En uns 6 mesos", "Només estic mirant"],
        "financiacion": "T'interessa que revisem la hipoteca?",
        "financiacion_opts": ["Sí, m'interessa", "No, ja la tinc resolta",
                              "Encara no ho sé"],
        "alq_presupuesto": "Pressupost mensual (€/mes)",
        "alq_duracion": "Per quant de temps?",
        "alq_duracion_opts": ["Menys d'1 any", "1 any", "2 anys o més",
                              "Temporada o estada curta"],
        "alq_entrada": "Des de quan el necessites?",
        "alq_personas": "Quantes persones hi viureu?",
        "alq_mascotas": "Tens mascotes?",
        "alq_mascotas_opts": ["No", "Sí, petita", "Sí, gran"],
        "alq_situacion": "Situació laboral (opcional)",
        "alq_situacion_opts": ["Contracte indefinit", "Contracte temporal",
                               "Autònom/a", "Estudiant", "Jubilat/da",
                               "Prefereixo no dir-ho"],
        "alq_acredita": "Pots acreditar ingressos? (opcional)",
        "alq_acredita_opts": ["Sí", "Parcialment", "Encara no",
                              "Prefereixo no dir-ho"],
        "prop_renta": "Lloguer mensual que esperes (€/mes)",
        "prop_amueblado": "Està moblat?",
        "prop_amueblado_opts": ["Sí", "Parcialment", "No"],
        "prop_disponible": "Des de quan està disponible?",
        "prop_mascotas": "Admets mascotes?",
        "prop_mascotas_opts": ["Sí", "No", "Segons el cas"],
        "prop_gestion": "Què necessites?",
        "prop_gestion_opts": ["Només trobar llogater",
                              "Gestió completa del lloguer",
                              "Encara no ho sé"],
        "col_agencia": "Agència o immobiliària",
        "col_zona": "Zona on treballes",
        "col_tipo": "Quin tipus de col·laboració busques?",
        "col_tipo_opts": ["Compartir cartera de venda",
                          "Compartir cartera de lloguer",
                          "Busco comprador per a un immoble",
                          "Busco llogater per a un immoble",
                          "Una altra"],
        "col_cartera": "Quants immobles tens en cartera?",
        "col_nota": "Explica'ns breument què busques (opcional)",
        "inmo_boton": "🏡 Vull assessorament",
        "col_boton": "🤝 Vull col·laborar",
        "inmo_gracias": "Gràcies, {nombre}! 🏡 Et contactarem molt aviat "
                        "per parlar de la teva operació.",
        "col_gracias": "Gràcies, {nombre}! 🤝 T'escriurem per estudiar "
                       "la col·laboració.",
        "privacidad_identificacion": "Pots sol·licitar les dades identificatives "
                                     "completes del responsable escrivint a {email}.",
    },
    # ------------------------------------------------ INGLÉS
    "en": {
        "modo_ahorro": "💡 Save on my services",
        "modo_inmo": "🏡 Property: buy, sell or rent",
        "modo_pregunta": "What are you interested in?",
        "inmo_titulo": "🏡 Buying, selling or renting?",
        "inmo_intro": "Tell us what you need and we'll guide you through the whole "
                      "process, **with no obligation**: valuation, search, "
                      "paperwork and signing.",
        "inmo_paso1": "1️⃣ Your transaction",
        "inmo_paso2": "2️⃣ Your contact details",
        "inmo_sello": "🔑 Guidance through the whole process",
        "inmo_sello_alq": "🤝 We work with other agents",
        "operacion": "What would you like to do?",
        "operacion_opts": [
            "Buy a property",
            "Sell my property",
            "Looking for a rental",
            "Rent out my property (I'm the owner)",
            "I'm an agent and want to collaborate",
        ],
        "tipo": "Property type",
        "tipo_opts": ["Flat", "House", "Penthouse", "Commercial premises",
                      "Land", "Other"],
        "zona": "City and country of the property",
        "residencia": "Which country are you writing from? (optional)",
        "ambito": "🌍 Properties across Spain · We assist buyers and owners from other countries",
        "habitaciones": "Bedrooms",
        "importe_compra": "Approximate budget (€)",
        "importe_venta": "Price you expect (€)",
        "plazo": "When?",
        "plazo_opts": ["As soon as possible", "In about 3 months",
                       "In about 6 months", "Just looking"],
        "financiacion": "Shall we review your mortgage too?",
        "financiacion_opts": ["Yes, I'm interested", "No, already sorted",
                              "I don't know yet"],
        "alq_presupuesto": "Monthly budget (€/month)",
        "alq_duracion": "For how long?",
        "alq_duracion_opts": ["Less than 1 year", "1 year", "2 years or more",
                              "Short stay / seasonal"],
        "alq_entrada": "From when do you need it?",
        "alq_personas": "How many people will live there?",
        "alq_mascotas": "Do you have pets?",
        "alq_mascotas_opts": ["No", "Yes, small", "Yes, large"],
        "alq_situacion": "Employment situation (optional)",
        "alq_situacion_opts": ["Permanent contract", "Temporary contract",
                               "Self-employed", "Student", "Retired",
                               "I'd rather not say"],
        "alq_acredita": "Can you provide proof of income? (optional)",
        "alq_acredita_opts": ["Yes", "Partly", "Not yet", "I'd rather not say"],
        "prop_renta": "Monthly rent you expect (€/month)",
        "prop_amueblado": "Is it furnished?",
        "prop_amueblado_opts": ["Yes", "Partly", "No"],
        "prop_disponible": "Available from",
        "prop_mascotas": "Do you allow pets?",
        "prop_mascotas_opts": ["Yes", "No", "Case by case"],
        "prop_gestion": "What do you need?",
        "prop_gestion_opts": ["Just find a tenant", "Full rental management",
                              "I don't know yet"],
        "col_agencia": "Agency",
        "col_zona": "Area you work in",
        "col_tipo": "What kind of collaboration?",
        "col_tipo_opts": ["Share sales listings", "Share rental listings",
                          "Looking for a buyer for a property",
                          "Looking for a tenant for a property", "Other"],
        "col_cartera": "How many properties do you currently list?",
        "col_nota": "Tell us briefly what you're looking for (optional)",
        "inmo_boton": "🏡 I'd like advice",
        "col_boton": "🤝 I'd like to collaborate",
        "inmo_gracias": "Thank you, {nombre}! 🏡 We'll contact you very soon "
                        "to talk about your plans.",
        "col_gracias": "Thank you, {nombre}! 🤝 We'll be in touch to look at "
                       "the collaboration.",
        "privacidad_identificacion": "You may request the full identification "
                                     "details of the data controller by writing "
                                     "to {email}.",
    },
    # ------------------------------------------------ PORTUGUÉS
    "pt": {
        "modo_ahorro": "💡 Poupar nos meus serviços",
        "modo_inmo": "🏡 Casa: comprar, vender ou arrendar",
        "modo_pregunta": "O que lhe interessa?",
        "inmo_titulo": "🏡 Compra, vende ou arrenda?",
        "inmo_intro": "Diga-nos o que precisa e acompanhamo-lo em todo o processo, "
                      "**sem compromisso**: avaliação, procura, papelada e escritura.",
        "inmo_paso1": "1️⃣ A sua operação",
        "inmo_paso2": "2️⃣ Os seus dados de contacto",
        "inmo_sello": "🔑 Acompanhamento em todo o processo",
        "inmo_sello_alq": "🤝 Colaboramos com outros agentes",
        "operacion": "O que pretende fazer?",
        "operacion_opts": [
            "Comprar casa",
            "Vender a minha casa",
            "Procuro casa para arrendar",
            "Quero arrendar a minha casa (sou proprietário)",
            "Sou agente e quero colaborar",
        ],
        "tipo": "Tipo de imóvel",
        "tipo_opts": ["Apartamento", "Moradia", "Cobertura", "Espaço comercial",
                      "Terreno", "Outro"],
        "zona": "Cidade e país do imóvel",
        "residencia": "De que país nos escreve? (opcional)",
        "ambito": "🌍 Imóveis em toda a Espanha · Atendemos compradores e proprietários de outros países",
        "habitaciones": "Quartos",
        "importe_compra": "Orçamento aproximado (€)",
        "importe_venta": "Preço que espera (€)",
        "plazo": "Para quando?",
        "plazo_opts": ["O mais depressa possível", "Em cerca de 3 meses",
                       "Em cerca de 6 meses", "Só estou a ver"],
        "financiacion": "Quer que revejamos o crédito habitação?",
        "financiacion_opts": ["Sim, interessa-me", "Não, já está resolvido",
                              "Ainda não sei"],
        "alq_presupuesto": "Orçamento mensal (€/mês)",
        "alq_duracion": "Por quanto tempo?",
        "alq_duracion_opts": ["Menos de 1 ano", "1 ano", "2 anos ou mais",
                              "Temporada ou estadia curta"],
        "alq_entrada": "A partir de quando precisa?",
        "alq_personas": "Quantas pessoas vão viver lá?",
        "alq_mascotas": "Tem animais de estimação?",
        "alq_mascotas_opts": ["Não", "Sim, pequeno", "Sim, grande"],
        "alq_situacion": "Situação profissional (opcional)",
        "alq_situacion_opts": ["Contrato sem termo", "Contrato a termo",
                               "Trabalhador independente", "Estudante",
                               "Reformado/a", "Prefiro não dizer"],
        "alq_acredita": "Consegue comprovar rendimentos? (opcional)",
        "alq_acredita_opts": ["Sim", "Parcialmente", "Ainda não",
                              "Prefiro não dizer"],
        "prop_renta": "Renda mensal que espera (€/mês)",
        "prop_amueblado": "Está mobilado?",
        "prop_amueblado_opts": ["Sim", "Parcialmente", "Não"],
        "prop_disponible": "Disponível a partir de",
        "prop_mascotas": "Aceita animais?",
        "prop_mascotas_opts": ["Sim", "Não", "Conforme o caso"],
        "prop_gestion": "Do que precisa?",
        "prop_gestion_opts": ["Só encontrar inquilino",
                              "Gestão completa do arrendamento",
                              "Ainda não sei"],
        "col_agencia": "Agência imobiliária",
        "col_zona": "Zona onde trabalha",
        "col_tipo": "Que tipo de colaboração procura?",
        "col_tipo_opts": ["Partilhar carteira de venda",
                          "Partilhar carteira de arrendamento",
                          "Procuro comprador para um imóvel",
                          "Procuro inquilino para um imóvel", "Outra"],
        "col_cartera": "Quantos imóveis tem em carteira?",
        "col_nota": "Conte-nos brevemente o que procura (opcional)",
        "inmo_boton": "🏡 Quero aconselhamento",
        "col_boton": "🤝 Quero colaborar",
        "inmo_gracias": "Obrigado, {nombre}! 🏡 Entraremos em contacto muito em "
                        "breve para falar da sua operação.",
        "col_gracias": "Obrigado, {nombre}! 🤝 Entraremos em contacto para "
                       "estudar a colaboração.",
        "privacidad_identificacion": "Pode solicitar os dados identificativos "
                                     "completos do responsável escrevendo "
                                     "para {email}.",
    },
    # ------------------------------------------------ FRANCÉS
    "fr": {
        "modo_ahorro": "💡 Économiser sur mes services",
        "modo_inmo": "🏡 Logement : acheter, vendre ou louer",
        "modo_pregunta": "Qu'est-ce qui vous intéresse ?",
        "inmo_titulo": "🏡 Vous achetez, vendez ou louez ?",
        "inmo_intro": "Dites-nous ce dont vous avez besoin et nous vous accompagnons "
                      "tout au long du processus, **sans engagement** : estimation, "
                      "recherche, démarches et signature.",
        "inmo_paso1": "1️⃣ Votre projet",
        "inmo_paso2": "2️⃣ Vos coordonnées",
        "inmo_sello": "🔑 Accompagnement du début à la fin",
        "inmo_sello_alq": "🤝 Nous collaborons avec d'autres agents",
        "operacion": "Que souhaitez-vous faire ?",
        "operacion_opts": [
            "Acheter un logement",
            "Vendre mon logement",
            "Je cherche une location",
            "Louer mon logement (je suis propriétaire)",
            "Je suis agent et je veux collaborer",
        ],
        "tipo": "Type de bien",
        "tipo_opts": ["Appartement", "Maison", "Penthouse", "Local commercial",
                      "Terrain", "Autre"],
        "zona": "Ville et pays du bien",
        "residencia": "De quel pays nous écrivez-vous ? (facultatif)",
        "ambito": "🌍 Biens dans toute l'Espagne · Nous accompagnons acheteurs et propriétaires d'autres pays",
        "habitaciones": "Chambres",
        "importe_compra": "Budget approximatif (€)",
        "importe_venta": "Prix souhaité (€)",
        "plazo": "Pour quand ?",
        "plazo_opts": ["Dès que possible", "D'ici 3 mois environ",
                       "D'ici 6 mois environ", "Je regarde seulement"],
        "financiacion": "Souhaitez-vous que l'on étudie le crédit immobilier ?",
        "financiacion_opts": ["Oui, cela m'intéresse", "Non, c'est déjà réglé",
                              "Je ne sais pas encore"],
        "alq_presupuesto": "Budget mensuel (€/mois)",
        "alq_duracion": "Pour combien de temps ?",
        "alq_duracion_opts": ["Moins d'un an", "1 an", "2 ans ou plus",
                              "Courte durée / saison"],
        "alq_entrada": "À partir de quand ?",
        "alq_personas": "Combien de personnes y vivront ?",
        "alq_mascotas": "Avez-vous des animaux ?",
        "alq_mascotas_opts": ["Non", "Oui, petit", "Oui, grand"],
        "alq_situacion": "Situation professionnelle (facultatif)",
        "alq_situacion_opts": ["CDI", "CDD", "Indépendant(e)", "Étudiant(e)",
                               "Retraité(e)", "Je préfère ne pas le dire"],
        "alq_acredita": "Pouvez-vous justifier vos revenus ? (facultatif)",
        "alq_acredita_opts": ["Oui", "En partie", "Pas encore",
                              "Je préfère ne pas le dire"],
        "prop_renta": "Loyer mensuel souhaité (€/mois)",
        "prop_amueblado": "Est-il meublé ?",
        "prop_amueblado_opts": ["Oui", "En partie", "Non"],
        "prop_disponible": "Disponible à partir du",
        "prop_mascotas": "Acceptez-vous les animaux ?",
        "prop_mascotas_opts": ["Oui", "Non", "Au cas par cas"],
        "prop_gestion": "De quoi avez-vous besoin ?",
        "prop_gestion_opts": ["Trouver un locataire seulement",
                              "Gestion locative complète",
                              "Je ne sais pas encore"],
        "col_agencia": "Agence immobilière",
        "col_zona": "Secteur où vous travaillez",
        "col_tipo": "Quel type de collaboration ?",
        "col_tipo_opts": ["Partager un portefeuille de vente",
                          "Partager un portefeuille de location",
                          "Je cherche un acheteur pour un bien",
                          "Je cherche un locataire pour un bien", "Autre"],
        "col_cartera": "Combien de biens avez-vous en portefeuille ?",
        "col_nota": "Dites-nous brièvement ce que vous cherchez (facultatif)",
        "inmo_boton": "🏡 Je veux être conseillé",
        "col_boton": "🤝 Je veux collaborer",
        "inmo_gracias": "Merci, {nombre} ! 🏡 Nous vous contacterons très vite "
                        "pour parler de votre projet.",
        "col_gracias": "Merci, {nombre} ! 🤝 Nous vous écrirons pour étudier "
                       "la collaboration.",
        "privacidad_identificacion": "Vous pouvez demander les coordonnées "
                                     "complètes du responsable en écrivant "
                                     "à {email}.",
    },
    # ------------------------------------------------ ITALIANO
    "it": {
        "modo_ahorro": "💡 Risparmiare sui miei servizi",
        "modo_inmo": "🏡 Casa: comprare, vendere o affittare",
        "modo_pregunta": "Che cosa ti interessa?",
        "inmo_titulo": "🏡 Compri, vendi o affitti?",
        "inmo_intro": "Raccontaci di cosa hai bisogno e ti accompagniamo in tutto "
                      "il percorso, **senza impegno**: valutazione, ricerca, "
                      "pratiche e rogito.",
        "inmo_paso1": "1️⃣ La tua operazione",
        "inmo_paso2": "2️⃣ I tuoi dati di contatto",
        "inmo_sello": "🔑 Assistenza in tutto il percorso",
        "inmo_sello_alq": "🤝 Collaboriamo con altri agenti",
        "operacion": "Che cosa vuoi fare?",
        "operacion_opts": [
            "Comprare casa",
            "Vendere la mia casa",
            "Cerco casa in affitto",
            "Voglio affittare la mia casa (sono proprietario)",
            "Sono un agente e voglio collaborare",
        ],
        "tipo": "Tipo di immobile",
        "tipo_opts": ["Appartamento", "Casa indipendente", "Attico",
                      "Locale commerciale", "Terreno", "Altro"],
        "zona": "Città e paese dell'immobile",
        "residencia": "Da quale paese ci scrivi? (facoltativo)",
        "ambito": "🌍 Immobili in tutta la Spagna · Seguiamo acquirenti e proprietari di altri paesi",
        "habitaciones": "Camere",
        "importe_compra": "Budget approssimativo (€)",
        "importe_venta": "Prezzo che ti aspetti (€)",
        "plazo": "Per quando?",
        "plazo_opts": ["Il prima possibile", "Tra circa 3 mesi",
                       "Tra circa 6 mesi", "Sto solo guardando"],
        "financiacion": "Vuoi che controlliamo anche il mutuo?",
        "financiacion_opts": ["Sì, mi interessa", "No, è già risolto",
                              "Non lo so ancora"],
        "alq_presupuesto": "Budget mensile (€/mese)",
        "alq_duracion": "Per quanto tempo?",
        "alq_duracion_opts": ["Meno di 1 anno", "1 anno", "2 anni o più",
                              "Breve periodo / stagionale"],
        "alq_entrada": "Da quando ti serve?",
        "alq_personas": "Quante persone ci vivranno?",
        "alq_mascotas": "Hai animali?",
        "alq_mascotas_opts": ["No", "Sì, piccolo", "Sì, grande"],
        "alq_situacion": "Situazione lavorativa (facoltativo)",
        "alq_situacion_opts": ["Contratto a tempo indeterminato",
                               "Contratto a termine", "Libero professionista",
                               "Studente", "Pensionato/a",
                               "Preferisco non dirlo"],
        "alq_acredita": "Puoi documentare il reddito? (facoltativo)",
        "alq_acredita_opts": ["Sì", "In parte", "Non ancora",
                              "Preferisco non dirlo"],
        "prop_renta": "Affitto mensile che ti aspetti (€/mese)",
        "prop_amueblado": "È arredato?",
        "prop_amueblado_opts": ["Sì", "In parte", "No"],
        "prop_disponible": "Disponibile da",
        "prop_mascotas": "Accetti animali?",
        "prop_mascotas_opts": ["Sì", "No", "Caso per caso"],
        "prop_gestion": "Di cosa hai bisogno?",
        "prop_gestion_opts": ["Solo trovare un inquilino",
                              "Gestione completa dell'affitto",
                              "Non lo so ancora"],
        "col_agencia": "Agenzia immobiliare",
        "col_zona": "Zona in cui lavori",
        "col_tipo": "Che tipo di collaborazione cerchi?",
        "col_tipo_opts": ["Condividere portafoglio vendite",
                          "Condividere portafoglio affitti",
                          "Cerco un acquirente per un immobile",
                          "Cerco un inquilino per un immobile", "Altro"],
        "col_cartera": "Quanti immobili hai in portafoglio?",
        "col_nota": "Raccontaci brevemente che cosa cerchi (facoltativo)",
        "inmo_boton": "🏡 Voglio una consulenza",
        "col_boton": "🤝 Voglio collaborare",
        "inmo_gracias": "Grazie, {nombre}! 🏡 Ti contatteremo molto presto "
                        "per parlare della tua operazione.",
        "col_gracias": "Grazie, {nombre}! 🤝 Ti scriveremo per valutare "
                       "la collaborazione.",
        "privacidad_identificacion": "Puoi richiedere i dati identificativi "
                                     "completi del titolare scrivendo a {email}.",
    },
    # ------------------------------------------------ ALEMÁN
    "de": {
        "modo_ahorro": "💡 Bei meinen Verträgen sparen",
        "modo_inmo": "🏡 Immobilie: kaufen, verkaufen oder mieten",
        "modo_pregunta": "Was interessiert Sie?",
        "inmo_titulo": "🏡 Kaufen, verkaufen oder mieten?",
        "inmo_intro": "Sagen Sie uns, was Sie brauchen, und wir begleiten Sie durch "
                      "den gesamten Prozess, **unverbindlich**: Bewertung, Suche, "
                      "Unterlagen und Unterschrift.",
        "inmo_paso1": "1️⃣ Ihr Vorhaben",
        "inmo_paso2": "2️⃣ Ihre Kontaktdaten",
        "inmo_sello": "🔑 Begleitung im gesamten Prozess",
        "inmo_sello_alq": "🤝 Wir arbeiten mit anderen Maklern zusammen",
        "operacion": "Was möchten Sie tun?",
        "operacion_opts": [
            "Eine Immobilie kaufen",
            "Meine Immobilie verkaufen",
            "Ich suche eine Mietwohnung",
            "Ich möchte meine Wohnung vermieten (Eigentümer)",
            "Ich bin Makler und möchte zusammenarbeiten",
        ],
        "tipo": "Art der Immobilie",
        "tipo_opts": ["Wohnung", "Haus", "Penthouse", "Gewerberaum",
                      "Grundstück", "Andere"],
        "zona": "Stadt und Land der Immobilie",
        "residencia": "Aus welchem Land schreiben Sie uns? (optional)",
        "ambito": "🌍 Immobilien in ganz Spanien · Wir betreuen Käufer und Eigentümer aus anderen Ländern",
        "habitaciones": "Zimmer",
        "importe_compra": "Ungefähres Budget (€)",
        "importe_venta": "Erwarteter Preis (€)",
        "plazo": "Bis wann?",
        "plazo_opts": ["So schnell wie möglich", "In etwa 3 Monaten",
                       "In etwa 6 Monaten", "Ich schaue mich nur um"],
        "financiacion": "Sollen wir auch die Finanzierung prüfen?",
        "financiacion_opts": ["Ja, gerne", "Nein, ist schon geregelt",
                              "Weiß ich noch nicht"],
        "alq_presupuesto": "Monatliches Budget (€/Monat)",
        "alq_duracion": "Für wie lange?",
        "alq_duracion_opts": ["Weniger als 1 Jahr", "1 Jahr", "2 Jahre oder mehr",
                              "Kurzzeit / Saison"],
        "alq_entrada": "Ab wann brauchen Sie es?",
        "alq_personas": "Wie viele Personen werden dort wohnen?",
        "alq_mascotas": "Haben Sie Haustiere?",
        "alq_mascotas_opts": ["Nein", "Ja, klein", "Ja, groß"],
        "alq_situacion": "Beschäftigungssituation (optional)",
        "alq_situacion_opts": ["Unbefristeter Vertrag", "Befristeter Vertrag",
                               "Selbstständig", "Studierend", "Im Ruhestand",
                               "Möchte ich nicht angeben"],
        "alq_acredita": "Können Sie Einkommensnachweise vorlegen? (optional)",
        "alq_acredita_opts": ["Ja", "Teilweise", "Noch nicht",
                              "Möchte ich nicht angeben"],
        "prop_renta": "Erwartete Monatsmiete (€/Monat)",
        "prop_amueblado": "Ist sie möbliert?",
        "prop_amueblado_opts": ["Ja", "Teilweise", "Nein"],
        "prop_disponible": "Verfügbar ab",
        "prop_mascotas": "Sind Haustiere erlaubt?",
        "prop_mascotas_opts": ["Ja", "Nein", "Je nach Fall"],
        "prop_gestion": "Was brauchen Sie?",
        "prop_gestion_opts": ["Nur einen Mieter finden",
                              "Komplette Mietverwaltung",
                              "Weiß ich noch nicht"],
        "col_agencia": "Maklerbüro",
        "col_zona": "Gebiet, in dem Sie arbeiten",
        "col_tipo": "Welche Art der Zusammenarbeit?",
        "col_tipo_opts": ["Verkaufsportfolio teilen", "Mietportfolio teilen",
                          "Ich suche einen Käufer für eine Immobilie",
                          "Ich suche einen Mieter für eine Immobilie",
                          "Andere"],
        "col_cartera": "Wie viele Immobilien haben Sie im Portfolio?",
        "col_nota": "Sagen Sie uns kurz, was Sie suchen (optional)",
        "inmo_boton": "🏡 Ich möchte beraten werden",
        "col_boton": "🤝 Ich möchte zusammenarbeiten",
        "inmo_gracias": "Danke, {nombre}! 🏡 Wir melden uns sehr bald, "
                        "um über Ihr Vorhaben zu sprechen.",
        "col_gracias": "Danke, {nombre}! 🤝 Wir melden uns, um die "
                       "Zusammenarbeit zu besprechen.",
        "privacidad_identificacion": "Die vollständigen Angaben zum "
                                     "Verantwortlichen können Sie unter {email} "
                                     "anfordern.",
    },
}


def ti(idioma, clave):
    """Devuelve un texto del embudo inmobiliario en el idioma elegido."""
    return TEXTOS_INMO.get(idioma, TEXTOS_INMO["es"]).get(
        clave, TEXTOS_INMO["es"][clave]
    )
